//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rTsd.Resources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rTsd.Resources.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Xamarin.Forms Android Projekt ist gedacht, etliche der einmaligen Features des kommenden Microsoft Surface Duos an einem praktischen Beispiel aufzuzeigen.
        ///
        ///Als Datengrundlage für die #rTsd-App dienen die freizugänglichen RSS-Feeds von, eines der größten deutschsprachigen Windows Portale mit angeschlossener Community, drwindows.de.
        ///
        ///Ebenso ist dieses Dr. Windows  Community Projekt auch da für gedacht den Spaß an der modernen Softwareentwicklung im Microsoft Ökosystem aufzuzeigen und den ein oder a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. Windows öffnen.
        /// </summary>
        internal static string AboutDrWindowsButton {
            get {
                return ResourceManager.GetString("AboutDrWindowsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll dasTwitter feature aktiviert werden? Es nutzt den twitrss.me Service..
        /// </summary>
        internal static string AboutFeatureSwitchTwitter {
            get {
                return ResourceManager.GetString("AboutFeatureSwitchTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub öffnen.
        /// </summary>
        internal static string AboutGitHubButton {
            get {
                return ResourceManager.GetString("AboutGitHubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road to Surface Duo mit Android und Xamarin.Forms..
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Xamarin.Forms Android Projekt ist gedacht, etliche der einmaligen Features des kommenden Microsoft Surface Duos an einem praktischen Beispiel aufzuzeigen.
        ///.
        /// </summary>
        internal static string FlyoutHeaderDescription {
            get {
                return ResourceManager.GetString("FlyoutHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road to Surface Duo mit Xamarin.Forms..
        /// </summary>
        internal static string FlyoutHeaderTitle {
            get {
                return ResourceManager.GetString("FlyoutHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aus der Sprechstunde.
        /// </summary>
        internal static string ItemsLatestNewsTitle {
            get {
                return ResourceManager.GetString("ItemsLatestNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuste Videos.
        /// </summary>
        internal static string ItemsVideosTitle {
            get {
                return ResourceManager.GetString("ItemsVideosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über diese App.
        /// </summary>
        internal static string NavigationAboutTitle {
            get {
                return ResourceManager.GetString("NavigationAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #rTsd - Road to Surface Duo - Ein Community Projekt von drwindows.de.
        /// </summary>
        internal static string NavigationHeaderSubtitle {
            get {
                return ResourceManager.GetString("NavigationHeaderSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NavigationNewsTitle {
            get {
                return ResourceManager.GetString("NavigationNewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaktiviert lassen.
        /// </summary>
        internal static string TwitterAlertCancelButton {
            get {
                return ResourceManager.GetString("TwitterAlertCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zur Anzeige des Twitter Tickers wird der Dienst twitrss.me benutzt. Bitte aktiviere das Feature nur wenn du damit einverstanden bist..
        /// </summary>
        internal static string TwitterAlertMessage {
            get {
                return ResourceManager.GetString("TwitterAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren.
        /// </summary>
        internal static string TwitterAlertOkButton {
            get {
                return ResourceManager.GetString("TwitterAlertOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker aktivieren?.
        /// </summary>
        internal static string TwitterAlertTitle {
            get {
                return ResourceManager.GetString("TwitterAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Feature ist im Moment deaktiviert. Schalte es in den Einstellunge an..
        /// </summary>
        internal static string TwitterDeactivatedMessage {
            get {
                return ResourceManager.GetString("TwitterDeactivatedMessage", resourceCulture);
            }
        }
    }
}
